CREATE TABLE [dbo].[DIM_CLIENTE]
(
	[COD_CLIENTE] NVARCHAR(50) NOT NULL PRIMARY KEY, 
    [DES_CLIENTE] NVARCHAR(200) NULL,
	[COD_CIDADE] NVARCHAR(50) NULL,
	[DES_CIDADE] NVARCHAR(200) NULL,
	[COD_ESTADO] NVARCHAR(50) NULL,
	[DES_ESTADO] NVARCHAR(200) NULL,
	[COD_REGIAO] NVARCHAR(50) NULL,
	[DES_REGIAO] NVARCHAR(200) NULL,
	[COD_SEGMENTO] NVARCHAR(50) NULL,
	[DES_SEGMENTO] NVARCHAR(200) NULL
	
)
