CREATE TABLE [dbo].[DIM_TEMPO]
(
	[COD_DIA] NVARCHAR(50) NOT NULL PRIMARY KEY, 
    [DATA] DATE NULL, 
    [COD_SEMANA] INT NULL, 
    [NOM_DIA_SEMANA] NVARCHAR(50) NULL, 
    [COD_MES] INT NULL, 
    [NOM_MES] NVARCHAR(50) NULL, 
    [COD_MES_ANO] NVARCHAR(50) NULL, 
    [NOM_MES_ANO] NVARCHAR(50) NULL, 
    [COD_TRIMESTRE] INT NULL, 
    [NOM_TRIMESTRE] NVARCHAR(50) NULL, 
    [COD_TRIMESTRE_ANO] NVARCHAR(50) NULL, 
    [NOM_TRIMESTRE_ANO] NVARCHAR(50) NULL,
    [COD_SEMESTRE] INT NULL, 
    [NOM_SEMESTRE] NVARCHAR(50) NULL, 
    [COD_SEMESTRE_ANO] NVARCHAR(50) NULL, 
    [NOM_SEMESTRE_ANO] NVARCHAR(50) NULL, 
    [ANO] NVARCHAR(50) NULL, 
    [TPO_DIA] NVARCHAR(50) NULL
)
